//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyThuVienCuaHung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOMUONSACH
    {
        public int MaBaoCaoMuon { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> SoLuotMuon { get; set; }
        public Nullable<int> TiLe { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
