//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyThuVienCuaHung.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BAOCAOMUONSACH> BAOCAOMUONSACHes { get; set; }
        public virtual DbSet<BAOCAOSACHTRATRE> BAOCAOSACHTRATREs { get; set; }
        public virtual DbSet<LOAI_DOCGIA> LOAI_DOCGIA { get; set; }
        public virtual DbSet<LOAI_SACH> LOAI_SACH { get; set; }
        public virtual DbSet<MUON> MUONs { get; set; }
        public virtual DbSet<PHIEU_MUON_SACH> PHIEU_MUON_SACH { get; set; }
        public virtual DbSet<PHIEU_THU_PHAT> PHIEU_THU_PHAT { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TAC_GIA> TAC_GIA { get; set; }
        public virtual DbSet<TRA_SACH> TRA_SACH { get; set; }
    }
}
