//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyThuVienCuaHung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUON
    {
        public int MaPhieuMuon { get; set; }
        public Nullable<int> MaSach { get; set; }
        public string MaDG { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
