//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyThuVienCuaHung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_MUON_SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_MUON_SACH()
        {
            this.TRA_SACH = new HashSet<TRA_SACH>();
        }
    
        public int MaPhieuMuon { get; set; }
        public string MaDG { get; set; }
        public int MaSach { get; set; }
        public System.DateTime NgayMuon { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SACH SACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRA_SACH> TRA_SACH { get; set; }
    }
}
